Day 4 - Puzzle 1

In [23]:
# @title
my_puzzle = """
@@..@.@@.@@.@@@@@.@@@.@@..@.@@@@@@@.@..@.@@@@@.@.@.@@@@@.@@.@@...@@@@.@@..@@...@.@.@@@@@@@@.@.@@@@@@.@@@@@..@@.@@@.@.@@@..@.@@@@.@@@@@..@@..
..@.@.@@@@@@@.@.@@@@@@.@@..@@.@@.@..@..@@@@..@.@.@@@@..@..@@.@..@@.@@.@@..@@@@.@.@@@@@@.@.@@@@@@@@..@@@@@@@@@@@@.@.@@.@@@@@@...@.@@.@@..@@.@
...@@@.@.@@@@@@....@..@.@@@@@@....@.@.@@.@@@@@@@.@@@.@@@@@@.....@@..@.@@..@..@@@..@@.@.@.@@..@@@@@@@@.@@.@.@.@....@.@..@@.@..@@@@.@@.....@@@
@@@@@@@@@@.@@@@@.@@@.@@.@@@.@.@@@@.@.@@.@@@..@.@..@@..@@.@@.@@@@..@.@@@@.@@@@@.@.@@@@.@.@@@@@@.@.@@@@.@@@@@@@@..@@.@@@.@@@..@...@@@@@@@@@@@@
.@@.@@@@@@@@@@@.@@@@.@..@.@@@@@.@..@@...@@@@@@@@.@@@@..@@@@@@..@...@.@.@.@@@@@.@@@.@@@.@@@.@@@@@@..@@.@.@@.@....@.@.@@@@@.@@@@..@@@@..@@..@@
.@@@@.@@@@@@@....@..@.@@.@@@@@@@..@@@@@@@@@@@@..@@@@@..@@.@..@..@@@.@.@@@@@@@@@.@@.@....@..@@@@@.@@@@@@@@.@@@@@@.@.@.@@@@@@@@.@.@.@@.@@@@..@
@@.@..@@@@@@@@@@...@...@@..@@@@@@.@@@@.@..@@..@...@@@.@@@.@@@.@@.@@@@@@@@@@@@@.@@@@@.@@@@@.@@@@@@@.@@.@.@@...@@.@@@.@.@@.@@@@.@@.@..@@@.@@.@
@.@@..@..@.@@@@@@@@@@.@@@...@@@@@@.....@@@@@@@....@.@@....@@.@@..@....@@.@@@@.@@.@.@...@..@..@@.@..@@...@.@@@@..@@@.@.@@@@@@@..@@@@.@@@@...@
.....@..@..@@@.@@..@@.@@@.@.@@.@@@@.@@@..@.@..@@@.@@@@....@@@.@@@@@@@@@.@.@.@@@.@@@...@@@@.@..@..@.@..@@@@.@@@..@.@@@@.@@...@@@.@@.@...@....
.@@@...@@.@..@@@@@@@.@@......@.@@@@@@@.@@@..@..@@.@@..@@@@@.@@@@@@.@@.@..@@@@@@@@..@@....@.@.....@@@@@@@.@..@@@@@.@@@..@@@@@@@.@@@@.@@@.@@.@
@@@@@...@@@@@.@.@@...@@@@@.@@@@@.@@@.@@@.@@@.@@@@.@@.@@.@.@@.@.@..@@...@@@@@@.@.@@@@@..@@@.@@@.@..@@@@.@.@@..@.@.@@@@@@@@.@@.@@@@.@@@@@..@@@
@..@..@@@@...@.@@@.@@@@..@.@@@@@@@@@@@@.@@.@@..@@.@@@@..@@@@@@@.@@@.@@@.@@@@.@.@.@@@@@@..@.@.@@@@@@..@@@.@..@@@@.@@@@.@@..@..@.@.@@@@@...@@@
@...@@@@.@@@@@@.@@@@@@@@@@@..@@.@@...@@.@@.@.@@@...@@@.@@.@@.@@..@@@@@@.@@..@.@@@@@@.@@@@.@.@...@@.@@@.@.@@@@@@.@@@@.@.@@.@.@..@@.@..@.@.@@@
.@@@@@...@.@.@@@@.@@@.@@.@@.@.@@@@.@@@@.@@@.@@@.@@@@@@..@@..@@.@@..@@@@@@@@@@@..@@@@.@@@@..@@@.@@@.@@.@@.@@@@.@@@.@.....@@@@@@@@@@@@@@@.@.@@
@.@.@.@..@@..@.@@@.....@@..@@.@@@..@@@@@@..@.@@.@@.@@.@@@@@.@@@.@@@.@@@.@@@@@@.@.@.@@@@.@.@@...@..@@...@@.@@@@@@..@@.@@@@.@@.@.@@@..@@@.@@@@
..@@.@@@@@@@@..@@.@@@@@@@@@.@.@@.@@.@..@@@@.@.@@.@..@@..@@@.@...@.@.@.@@.@@.@.@.@.@@@..@@@.@.....@@.@@@@@@@@@@@@.@.@..@....@..@@.@@@@.@.@...
.@.....@@@.@.@@@@@@@..@@.@@.@@.@@@@.@@@@@@.@.@@@@@.@@@@@.@@@.@@@@@@@.@@@@.@@@@...@@.@@@@.@@.@@.@@..@@..@@..@.@@@@@@@@..@@@@@@@@@@.@@@@.@..@@
@@@.@@.@.@@..@@@@@@@.@@.@@@.@.@@@@.@@.@......@.@@@.@.@@..@@@...@...@@.@@@@..@@@.@.@@..@.@@.@.@.@@@@@@..@@.@@.@@@@.@@@.@@.@....@@@..@.@@..@@@
@@.@...@.@@@.@.@..@@.@@.@@..@...@@@@.@.@@@@..@....@@.@.@@@..@@.@@..@@@@@..@@@.@@.@@.@..@@@@@..@@.@.@..@@.@.@.@.@@@@..@@..@@@@@@@@.@@.@@@.@@@
@@@@..@@@@..@@@@@.@@.@@@@.@.@@@@@@.@..@.@@@..@@@@@@.@@.@..@@..@@@@@...@@.@@@@@@..@@@@..@.@..@@@@@.@....@.@.@@@.@.@@@@@.@@.@.@@@.@.@@..@.@@@@
.@@@@.@.@...@@@@@.@@...@...@@..@..@.@.@@.@@.@.@.@@@..@@..@.@@.@..@..@@@@@.@.@..@@@.@@..@@.@.@@@.@..@@@@@...@@.@.@@@@.@@@@@@@@@@@@@@...@.@@..
@@@@@@..@.@@...@@.@@..@@@@..@@@@.@@@.@@.@@..@@@...@@@@.@@...@@@@..@@.@..@...@..@@@.@@@@.@@@@@@.@@@.@.@@@@@..@...@...@..@@@@.@.@@@@@@@@@@@..@
@@@@@@..@@@@@...@@@@..@@..@...@@.@@..@@@@@.@@@@@@.@.@@.@@.@@@@@@@@@.@@@@.@@@@@@@@.@..@.......@.@@@.@.....@..@@@@@@..@@@.@@@.@@..@..@@@.@@@@@
@@@@@.@.@@..@.@@@..@@@@....@.@.@@.@@@.@@@@@@.@.@.@@@..@@...@@@@@@..@.@.@@@.@.@.@@@@@.@@.@@@...@@@.@@.@@@@@..@.@@@@@.@.@.@.@@@@.@@@@@.@@@@@@@
.@.@@@.@@@@.@@.@@..@.@@...@.@@.@@.@.@@@@@@@.@@@@@@@@@..@@.@@..@@@@@@.......@@.@@@.@@.@@.@@@..@@@@@.@.@..@@@@@@@@@@@@.@..@@.@.@@@@@.@.@....@@
@@.@@.@@.@..@..@.@@@@@@@@@.@@@.@...@@.@@@@@@.@@@@@@@...@....@.@.@@@@@@@..@@@@@@@.@@@@.@@@@@@@@.@@....@.@@@..@.@.@@.@...@.@@@..@@......@@@@@@
@@@@.@@@@.@.@@@.@@.@@@@.@@@.@...@.@.@.@@@@.@@@@@@...@.@.@@.@..@@@@@.@@@@@@.@.@.@.@@@@@@@...@....@.@@.@.@.@....@.@.@@.@@@.@.@@.@@@@@.@@@@..@@
@..@.@.......@@@@@..@@.@@.@@@@.@..@@.@.@.@.@@@.@..@.@..@@.@@@@@@@...@@@@..@@@@....@@@..@@..@@@.@.@@..@@@..@@..@@@@@@@..@@.@.@@..@@.@@.@.@@@@
@.@@@@@@@@.@..@@@.@@@@...@@@.@@.@@@@@@@@@..@@.@.@...@@@@@.@.@.@..@..@..@@@.@..@@..@@@@@.@.@@@..@@.@@@@@.@.@.@@....@@@....@.@...@@@@.@@@@.@@.
@..@..@.@@@@..@@@.@.@@@@@@@@.@@.@@@@@.@@@@@..@@..@.@.....@@.@...@@@...@.@@@@@.@@@@@@@@.@@@@...@.@.@.@@@@@.@.@.@.@@@@@@.@@@@.@@.@@.@@@@@@@@@@
@.@@.@@@@@@.@@..@.@@@@....@.@.@.@@.@.@.@@..@@.@.@.@.@.@.@.@...@@@@.@..@@..@.@@@.@.@.@.@..@@@@@.@@.@@@@@@.@@.@@@.@.@@@@.@@@@@@@@@@.@..@.@@..@
@..@.@@.@@..@@@@@@.@@@@@@@@@.@.@@@@...@@.@@.@.@.@@.@@@.@....@@@.@.@@.@@.@.@@@@@@.@..@@.@@..@.@...@..@.@@..@@...@..@.@@@@.@@@.@@@..@@@@@@@@@.
@.@@@...@@.@@@@.@@..@@.@@..@.@@.@@@@...@@@@@..@@..@@.@@@@.@@@@.@@.@..@@@@.@.@@@@@@@.@@@@.@@..@@.@@..@@@.@@.@@@@@@.@@.@@@@@@@@@@@@@.@@@@@@@@.
.@@@@.@@@@.@.@@.@@@@@.@..@.@@@.@.@.@@@..@@@@@@@.@@..@..@@.@@@@..@.@.@@@..@....@@@@@@.@..@..@@@..@@@@@.@@.@@.@@..@@@@@@@@@@@..@@.@.@.@.....@@
@@@@@@..@@@@@@@..@.@@@.@@@..@@@@.@@..@@.@@..@..@...@@@@.@@@@@.@@@@@..@.@@@.@....@@@@@@@@.@..@@.@@.@@@.@..@@..@@@@@@.@@@.@.@@.@..@@@@@@@.@.@@
@.@@..@.@@@.@@@@.@@@@@@@@...@.@@@@@@@@.@@@@@..@@@.@.@@@.@@@..@.@..@@@@@@.@@@@@.@@..@@@.@@@.@@@@.@@@@@@@@@.@.@@@@.@@@..@...@.@@@@@@...@@@@@@.
@@..@@@@@@@@@.@@@@@@@@@@@.@@.@@.@@@@.@.@@.@..@.@.@.@@.@@@@.@.@@.@...@@..@.@@.@@.@.@@@@@.@@..@@@@.@@.@@@.@@@@@..@.@@@@@.@@..@..@.@...@@@.@.@@
@@@@.@@@@.@@@.@.@@@...@@.@@@@.@@...@@@@...@@.@@.@@.@@@@@@...@.@...@..@...@@@@@.@@@@..@.@..@@@@@@@.@..@.@@@@@@@.@.@@@.@@.@.@.@@..@@.....@@@@.
.@@.@@.@.@@@@.@@.@..@.@.@@.@@@.@@.@@.@@.@.@..@.@@@.@@@@@@@@@@@@...@@@@@@@@@.@@.@..@.@.@@@.@...@.@@@@@@@@@@@..@.@@@@..@..@@...@@@.@@....@..@.
@@....@@.@@@@.@.@.@.@@@@@@@@....@@@.@@@@@@..@@.@@.@.@@@@@.@@@.@..@..@....@@@@@.@@@....@.@..@..@@@.@..@..@@..@.@.@@@@@.@@..@...@@@@@@..@@@@@@
.@@.@@.@.@.@.@..@@@.@@.@@@...@@.@@@.@@.@..@@.@@@.@@.@@@@.@@.@@@@.@@@@@@@@...@..@@@..@@@.@@.@.@..@@@@@@.@@.@@@.@..@..@.@.@@@@@..@@@@@.@@.@.@.
@@..@@.@@@.@.@@@..@@@.@@@@.@.@@@@..@@@@@@@@.@.@.@@@.@.@@@@@@@..@.@@@.@@@@...@@@.@@@@.@@@@.@@@@.@@@@.@@.@.@@@.@.@@@@@@.@@@..@@.@.@.@@...@@@.@
@@@@.@@@@.@@@@@@@@..@@@@.@@@.@...@..@..@.@@@@.@@@@@@@@@@.@@...@.@@@@@@...@@@...@@@@..@@@@@@.@@.@@.@.@@@@@.@@@.@.@@@@@@@@@.@@@@@@@@@@@....@.@
@@.@@.@.@@@@@@@.@@@.@@.@@@@@@@@@....@.@..@@@@@@.@@..@@@@...@..@@..@@@@.@.@@@@@@@@@@.@.@@@..@@@@@.@@@@....@.@@.@.......@.@@.@@@@@@@@@@@.@@.@@
@@@@.@@@...@@@.@@@..@@......@@.@.@.@@@@@@@@@@@.@..@@@@...@@@..@@.@.@...@.@.@@.@@.@@@...@.@@@@@@@@@.@@@@@@@@..@.@@.@.@.@@.@@@.@.@.@.@@@@@@@.@
@@@@.@@@...@@.@@.@@@..@...@@@@@@.@@@@@@@.@@@...@.@@@@@.@@@...@..@@@..@@@@.@@@.@.@.@.@.@@..@.@.@@..@..@@@..@@@.@.@@@.@@...@@.....@..@...@@@@@
@@@...@@@@@.@@.@@@@@...@.@@@.@@.@.@@@@@@..@@@.@.@@.@@.@@@@.....@@.@.@@.@@@@@..@@.@.@@...@@@.@.@@@@@.@@@...@@..@@@...@.@@@@@...@@@@@.@@@@@@@.
.@@@@@.@..@.@@...@@@@.@.@.....@..@@..@@@@@..@@.@@@@@@.@.@@@@@..@@.@..@@..@@@.@.@@.@@.@.@...@@@@@.@@.@.@..@@@.@@@@...@..@.@.@@@@@.@@..@..@@@@
@..@.@.@.@@@.@@.@.@@.@@.@@@@...@.@...@.@..@@@.@...@@@....@@@@.@@@@@@.@@.@@.@@.@@@@.@...@@@@@..@@..@....@.@@@@@@@@..@@@.@@@.@@@@@@@...@.@..@@
..@@@....@.@@@@@@@@..@..@@.@@@@...@...@@.@@@@.@@@.@..@@.@@@@@@@.@@....@@@@@.@@@.@@.@..@@@.@@.@..@@@@@@@...@...@.@@@@@.@.@@...@@@.@@.@.@@..@@
@@.@@@@@..@@@@...@@@@@..@..@...@@@@@.@@@@.@@@@@@@@@@...@.@@@@@@.@@@.@@@@@..@.@@.@@.@..@@@@@...@@@.@@@@@.@@.@@@@@@.@..@@@.@@@.@@@@@..@..@@.@.
@.@@@.@.@@.@@@..@@@@@@...@.@@.@.@@.@@@..@..@.@@@.@@@@@.@@@.@@@@@..@@.@...@.@..@.@@.@@.@@@@@..@..@..@@.@@@@...@@@.@.@@@.@@...@...@..@@@..@..@
@@@@@@@@@.@@@.@.@@@@.@..@.@@@.@.@..@@@..@@.@.@.@@.@@..@@@@.@@..@.@@@@@@.@@..@@@@@.@@@@.@@@@@@@@@@.@@.@...@@@@@.@@.@@@.@@.@.@@..@.@@.@@..@@@@
@.@@@@.@@..@@...@@@.@@..@.@@.@@.@@@.@.@.@.@@@@@@@@@@@@@@@.@@.@@@.@@.@@@.@@@@@@@@.@.@@@@@@.@@..@..@@@@@@.@@@@@@@@@@..@@..@@@.@.@@@@@.@@.@..@@
@@@..@.@.@@.@@@..@@..@@@.@@.@@@@@@@@@@@@.@@@@@.@@@...@@..@@..@.@.@.@@..@@@.@@@@@@@@@@..@.@..@..@@@@@.@@@....@..@@.@..@..@@.@...@@.@@@@@@@@.@
@@@.@@..@.@@.@@.@@@@@@@@...@@@@@.@@@@@@@.@.@@@.@..@@..@@..@@@@@@@@@@@@.@@...@@@@@.@....@@@@.@@....@@.@.@..@.@@.@@.@@.@@@@@..@.....@.@@@@@@@@
@...@.@@@@@@@.@@...@...@@@.@@@.@@..@@.@.@@@@@@@.@.@@.@@@.@@@@.@@.@@.@@@@@@.@@@@@@.@..@@@@@@@.@..@@@.@.@@@@.@...@@..@@@...@@@@...@@.@.@@.@@@@
.@@@.@@@@@@@@.@..@@..@.@@@@..@@@@.@.@@..@@@@@@@@.@@@@@...@..@@.....@...@.@.@...@@@@@@@@....@@@@..@.@@@@@@.@.@@@..@.@.@.@.@@@.@..@.@@@.@@..@.
.@@@@@@@@..@.@...@@...@.@.@@.@@@@@@..@...@@@.@@.@@.@..@@..@@@@.@.@....@@.@@@@.@@.@.@@.@@...@@@@@@@..@@@..@@@@@@@@..@@..@@@..@..@.@.@@.@@@@.@
@@.@@...@@@.@@.@@@@@@.@@@.@@@@@..@.@@@..@@.@..@.@@@.@@@@@@.@@@.@.@@@.@@@@.@.@..@....@...@@.@@@@@@.@@@@.@...@@@@@@@@@.@@@@.@@@@@.@@@@...@@@@@
@@@.@@..@@.@@@@@@.@.@@@@@@@@.@@@@@@@@@.@@.@@.@@.@......@.@.@.@.@@...@..@..@@.@@@.@@@.....@.@.@@....@.@@@....@@@.@.@.@.@@@@@@@@@@@.@@@.@@@@..
@.@@@@@...@..@@@@@@@..@..@@@.@..@.@@@@@@@...@@@@@@@.@@@@.@@..@.@..@@@@@..@..@@@.@@..@.@@@@@..@@.@@@.@.@@@@@@@..@..@@..@.@@.@@@@@@@.@..@@.@@.
..@@@@@@@.@@@@@@@@.@@@.@@@.@@@..@@.@@@@@@@@..@@@.@..@@@@@....@@@@.@@.@@.@.@@....@..@@.@@@@@.@@.@.@.@@@.@@.@@@..@@@@@@.@@@.@@@.@@.@@.@@.@@@@.
.@@.@@.@@@@@.@.@.@.@@@..@@@.@@@@@..@@.@....@...@@.@@@..@@.@@@.@@@.@@@@.@....@@..@@@.@@@@..@@..@.@.@@@.@@@@.@..@@@...@@...@@.@...@@@...@..@.@
@@@@@@@@@@.@@..@@@...@@@@@@@@..@.@@..@@....@@@@@@.@.@@@@@...@.@..@@@@..@@@@@..@.@@.@@@@..@@@@@@..@.@@@...@@@@..@@.@.@@..@@@@@.@@@@@.@.@@.@..
@@.@@@@@.@@@@.@.@.@@@@@@@.@@@...@@@@@@@@@@@@.@@@..@@@@@..@.@@@@@.@@.@@@@..@@..@.@.@.@......@@...@@@.@@..@@@@@@.@@@@@...@..@@@@@.@@@@@.@@..@.
@..@@@@...@.@@@@@..@.@@@.@.@..@@@@..@.@@@@.@...@@@@.@...@@.@@@@@@....@.@@@.@@@.@@.@@@.@@@@@@.@..@....@..@@@..@.@.@@..@@@@@.@@@@..@@.@.@@@.@@
.@@@@..@@@..@@.@.@..@@.@@.@@@...@..@.@@@.@.@@.@.@@@....@@@.@@@@@@@@@@@@@@.@..@..@@..@@@.@@@@@.@.@@..@@.@.@@.@@@@@@@.@.@...@..@@@@@@@@..@@@@@
@.@@@@.@.@.@@.@@@..@@@.@@@..@@@@@@@.@.@.@@@...@@@@.@.@.@..@@@..@@@.@@.@.@@..@@.@.@@@.@..@.@.@@@@@..@@@@@@@.@.@..@@.@.@.@@@.@.@..@.@@.@@@.@@.
@@@.@@@@@@.@@@@.@.@@@@.@@.@..@.@@..@.@...@@@@.@.@.@.@@.@@@....@@@@@@..@.@@@.@@@.@@@@..@@@@@@.@@@.@@@@@@....@.@...@@@@.@@@@@@.@@@...@.@@@.@@@
@.@@.@@@@@@@@.@...@@..@@.@@@@@@@.@.@@@..@@@@@.@@@@@.@@@@.@@.@@.@@....@@@@@@@..@.@@@@@@@@@@..@...@.@.@@.@@@.@@@..@@@...@..@@.@@..@@..@.@@@@@.
@.@@..@....@@@@.@..@@@@@@@@@@...@@@@..@@@.@@...@@@.@..@@@.@.@@.@@@@@@.@.@@@@@@@@@@@@@@@@.@@.@@.@@@@@@@.@@..@@@@@@@@@.@@@@@@@.@@.@.@.@@.@@@@@
@.@.@@@.@@.@@@.@@@@@..@@@.@.@.@.@@@@@.@@..@@@.@@@@@@@@@@.@@@@@.@@@@@@.@@@.@@@@@@.@@.@@@@.@..@@@@@@..@@@@@.@@.@@@@.@@..@@.@@@@.@.@.@@@@@...@@
@@@@@..@.@@@..@..@.@@@@...@@.@@@@@@..@@.@@@@.@..@@@.@.@@.@@@@.@.@@@@.....@...@@....@.....@@..@.@@@@@.@@@.@@@@..@@.@@.@@@..@.@@@@@@@.@..@.@@@
.@@@..@@@@@.@@@@.@.@.@@.@@@.@.@....@..@@.@@@..@.@@@@@@.@@@.@@..@..@.@.@.@@@.@@..@@@....@@@..@@@@@@@@.@@@@@@@..@.@...@@@.@@@@@..@@..@@.@.@@.@
@..@@@.@@..@@.@@@@@....@@@@@@@..@@@@.@.@@@..@.@@@.@@@@@@@..@@.@@@@.@..@.@@.@..@@@@..@@@.@..@@@@@.@@.@@..@@@.@@@@.@..@.@@@@.@.@@@@.@@@@@@@@.@
.@@@@@.@@@.@@@@@@@@..@@@..@@.@@@@@@@.@@@.@.@.@.@@..@@.@...@@@@.@.@@.@@@..@.@@@@...@.@@.@@@.@@@..@@@.@.@.@..@@@@.@...@@.@....@@@.@..@@@.@@.@@
@@..@@.@.@@@@@@.@.@.@.@@@@.@@..@@@..@@..@..@..@@.@@@.@@.@@@@@@@@.@.@@.@.@@@@...@@@@.@.@@@.@@@@...@.@@@@@@@@@@@@.....@.@@.@@..@@..@@@..@@@.@@
@@@.@@@@@.@.@@.@@.@@.@.@@@@..@@@..@..@.@@.@@.@@@@@...@@@.@@..@.@@@.@@.@@@@@@@@@@@..@.@@@.@.@@..@@.@.@@@.@@.@@@@@.@.@@.@@@@@@@@@@@@..@@...@@@
..@@@@@@..@...@@@@.@.@@@@..@.@@@@...@..@@@@@@@@@@.@@@..@@@.@@..@@@.@@@@@@..@@@@.@@@@@@@@.@...@.@@.@@@@@@@@@..@@@@..@.@.@@@@..@@@.@@@@@@.@@@.
@@@@...@@@@@@@@.@@@@@@@..@@@@@@...@@...@@@@@.@.@@.@@@.@@@..@.@.@@@@@@@@...@@@@@..@.@@@@@@@@@.@@.@@@@@@@@@@.@@@@...@@@@@@@.@@@..@...@@@.@...@
@.@@@@@.@@.@..@@@@@@@@@@@.@@@@.@@.@@@.@@.....@@..@@@@@.@@..@.@@@.@@@...@@@.@@@.@.@.@@.@.@.@@..@.@@@@@@..@.@@.@..@@@.@@@..@@@@...@..@@@@@@...
@@@@.@@@.@.@@@@.@@@@@@@....@@@@@....@.@..@@@.@...@@@.@@..@@@...@..@@@@.@.@.@...@.@@@@@@@@.@@@.@@@.@.@@@.@@@.@.@.@@@.@.@@@@@@@..@@@@@...@.@.@
@.@@@.@.@.@@@@@@.@..@@.@.@@.@.@.@.@@@@..@@..@...@@@@@..@.....@@@@..@@.@@@.@.@@@@@@@@@..@.@..@@@.@@.@@@...@.@@@@..@...@@@.@..@@@@..@@@@.@@.@@
@@@@.@.@..@.@@.@@..@.@.@@@..@.@@@.@@@@.@.@@@@@@.@.@@@@@@@@@.@@@.@.@@@@..@@@.@@.@@.@@@@@....@..@@.@@@@.@..@@@@@.@@@@..@@@@@@...@@@@.....@@@@.
.@.@.@@@@@@.@@..@@@@@@@@@....@@@@.@@.@@.@@@.@@@..@.....@@@@.....@@..@@..@@@@@@@@@@.@@@@.@.@@@@@..@@.@..@@.@.@@@@..@.@@@.@.@@.@.@@.@@@.@...@.
.@..@@@@.@@@.@@@.....@@@@@@.@@@@..@@.@@@.@@..@.@@....@.@..@@@.@.@@.@@@...@@@.@@.@@@@@...@.@@@.@@@.@.@@@.@@.@@@@@@@..@@.....@@@.@@.@@@@.@@@.@
@@@@.@.@.@..@@@..@.@@@@@@@.@@@.@@@.@@@.@@.@.@@.@..@@..@@.@@@.@@@.@@@.@@@..@@.@..@..@@@..@@@@..@....@....@..@@..@@@.@.@.@@.@@@@@@@.@@.@@..@@@
@@.@@@@@@.@@..@@...@@@@.@@@.@@.@.@.@@.@@@.@.@@@@@@@.@@@@..@@.@.@@@@@.@@@@.@.@...@@.@.@@...@@@@...@.@@@...@...@@.@..@.@@@..@..@.@@@@@..@..@@.
@.@...@@.@@@..@@@@@@@@.@..@@@@@@@@@@@...@.@.@@@@@..@@@@@..@.@@.@@@..@...@@..@@@@..@.@@@@@.@@..@@@.@@@@@@@@.@.@@@@..@@.@.@@@@...@...@@@@..@@@
@..@@@@@...@.@...@.@@@@@@@...@@.@.@.@@..@@@@@@.@@@@@@@@...@@@..@.@..@.@@@..@.@.@...@@@.@@@@@@..@@.@@@@@.@.@@.@@@@@@@@..@@..@@@@@@@@@@@.@@@..
@..@@@@@.@@@@@@@@..@@@@@.@@@.@@.@@@@@@.@@@.@@@@.@@@.@.@@...@...@@@.@@@...@@@....@..@@@@@@..@@@@@@.@.@@@.@@.@.@@@@@@@@@.@@@@..@@@@...@.@@..@@
@@.@@@@@@@.@.@@@.@@@@.@.@...@@.@.@....@..@@@@.@@@.@@@.@@.@@@@@...@.@..@@@.@..@@@@..@.@@..@@.@@.@...@@@@..@..@@.@.@@@@.@.@@.@@@...@.@..@@@@.@
@@.@@@@.@@..@@.@@.@..@@@@@@.@..@@.@.@@@@@@.@.@.@.@@@@@.@@@..@..@.@@@@@....@@...@@.@.@@@@@@..@@.@..@@@.@@@@@@@@.@@.@@..@..@..@@@@@..@@@.@@.@.
@@@@@@@.@.@@@...@@@.@@@@..@@.@@@.@@@@@..@.@.@@..@@..@...@.@@@@.@@@@@@@@@..@.@.@.@@@@@@..@@@..@.@..@..@@.@@.@..@@@@@@@@@@....@@@@....@.@.@@@.
@@.@@@.@@@@.@..@@@@@.@@.@.@.@.@@..@.@.@.@@@@@.@@@@.@@..@@...@@.@.@@@..@.@@@..@@@@@.@@@@.@@@...@.@@@@@@.@@.@.@..@@@.@@..@.@@.@@@@@.@@.@..@..@
.@.@@@@@.@@@@@......@...@@@..@.@@@@@@@@...@@.@..@..@@.@@.@.@@@.@.@@..@@@.@..@@@.@@.@@..@@@@@....@@.@.@@@@@...@@@.@@@@..@..@@@@@.@..@@@@@@.@.
.@@.@@@@@..@@@.@@@@....@@@..@@.@....@@@.@.@@@...@@@@.@..@@@@..@.....@.@@@@@@.@@@.@@..@.....@@@.@.@@@@..@.@@@@@@@.@@@.@@.@@.@...@@@@@@..@...@
@@@@@@.@@@@..@..@.@@@@@@@@@@.@@@@@.@...@@.@@.@@.@.@@.@@...@@@..@@@..@@....@@@.@.@.@@@@@..@.@@.@@.@@@@@.@@@.@.@@@@@@@@@@.@@@..@@@@@@...@.@.@@
@@.@@.@@@..@@.@@@..@@@@@@.@.@@@@.@@.@@....@@.@.@.@@@.@@@@...@..@@.@@@@..@@.@@......@.@.@@..@@@@@.@@@.@.@@.@@.@@@.@...@@@@.@.@@@.@@@@@@@@..@@
@...@.@.@@.@.@@@@..@.@..@@@@@@@@@..@@@@@@@.@@@@@...@@@.@@@@@.@@.@.@.@@@@.@@@.@@@.@@@@@...@.@.@@.@@.@@@@...@@.@.@@@@.@@.@..@@@..@@@@@@..@.@.@
@.@@@@@@@..@@@@.@...@.@.@@@@...@.@@.@@.@..@@@@.@@@.@@@..@.@@@.@.@@..@..@.@....@.@@@.@@@@..@.@@@@@@@...@@@@@@@@@@@@@.@@..@@@...@.@...@@@..@@@
@@@.@@@.@.@..@.@@..@.@@@@@@@@@@...@.@.@@@@@@@.@.@@@.@@.@.@@@@..@@....@@@@@...@.@.@@@@@.@@.@@@@.@.@@.@.@@@...@@@.@.@.@@...@@@......@@@@@@@.@.
.@@@@.@@@@@@.@@@@@.@@.@@@@@@@@.@@@@@...@@@@.@.@@@@......@.@@@@@..@@@@@.@@.@@@.@@@@@.@@..@@@@@@@.@..@@.@...@@@@.@.@.@@..@@.@@@@..@...@@.@@@@.
@@@@@@@@.@@...@@@@@@.@.@...@.@@@.@@@@..@.@@....@@@@@@@@.@.@@@.@@@.@.@@@@.@@.@..@@@.@@@@..@@.@@@..@..@...@@.@@@@@.@@@.....@@@@@.@@.@.@..@@@@@
@@@.@..@@.@@@.@..@.@@.@@.@.@.@@@@@..@.@@.@@@.@@@@@...@@@@@@.@.@.@@@..@@@@.@@..@.@.@.@@..@@.@@@@@.@..@.@@@@@...@@@@@@@@@.@@@..@.@@.@.@@.@@@@.
@@.@@@@@..@@@..@.@.@@......@@@.@@@@@..@@@..@@@@.@@@.@@@.@@@@.@.@@..@@.@.@@..@...@.@@.@@@..@.@.@.@@@@..@@@@@@.@@.@..@@...@@...@.@@@.@@@.@@.@@
@.@@@...@.@@@@@@.@@@@@@.@..@@@@@.@.@@@@@..@@.@@@.@@.@@@@@@@@@@.@..@@@@@@@@@..@@@.@.@@.@@@@@@@.@..@@@@@..@...@@.@@.@@.@@@.@@@@@@@@@....@@@.@@
@@@@@@@.@@@@.@..@@@.@.@@@@@.@@@@@@.@...@@@@@.@@..@@@@@@@@@.@@@@.@@@.@@.@@@@.@@@..@..@.@.@@@@@@.@....@@..@@.@.@@@..@..@@@@@..@@@@..@.@@@.@@@@
@..@@.@@.@@...@.@.@@@@@@@@@...@...@.@@.@.@@.@@@.@@@.@@..@.@@@....@.@.@@@.@@@@@@@@@@@@@@@@.@@@@@@@.@@@@..@.@@@@@.@@@..@.@@@@@@.@@@@.@@@@.@@.@
@@@.@@@@..@.@@@.@.@@....@@.@@..@@..@@@@@@@@@.@..@@@@@.@@@.@@...@.@@@@@@.@@@@.@.@@@.@@@@..@@@@.@....@@.@@@@..@.@.@.@.@@.@.@.@@@.@..@..@@@@@@@
@@@.@@@.@@@.@@@@..@.@@@@@@@@@@@.@..@..@@@@@.@@@@@..@@@@.@..@..@.@.@..@@.@@@@@@@@@@@@...@@..@@.@...@.@.@.@@.@.@@.@@@...@....@.@.@@@@...@.....
@@.@@@.@@@@@@@.@@@@..@...@@@@..@@@@@@@.@@@..@.@@@@@@.@@@...@@@.@@@@...@@@.@@@....@@.@@.@.@.@@@@@.@@@@@@..@...@@@@.@.@..@..@@@@@@@..@@@.@@@@.
@.@.@.@.@@@.@@.@@@@@.@@..@.@@..@.@..@.@@@.@@.@..@.@@@@@.@..@.@@@@@.@@.@@@.@@@@.@.@@@@@..@.@...@.@..@@.@@@@@@..@.@@@.@@...@.@@@.@@.@.@@..@.@@
@.@@..@.@@@@@@@@@.@@..@..@@...@@@..@.@..@@@@@.@@@@@@@@@@.@.@@@@.@@@@@@@@@@@@.@@@@@@..@@.@.@@@.@@@.@.@..@@@@@.@.@@@@@...@@.@@@.@@.@@@..@@..@@
@@@@...@@@@@..@@.@@.@@@.@..@@@.@@.@.@.@..@@.@@@@...@...@..@.@@@@.@...@@.@.@.@@..@......@@@.@@..@....@.@@@@.@@@.@@.@@@....@@@.@@.@.@..@@.@.@.
@.@@..@@@@@@@.@.@@...@.@.@@@@.@@@.@.@..@@@@@..@..@.@..@..@.@..@....@@.@..@@@@@@.@.@@@@@@@@@@@@@..@..@@.@@@@@.@@@@@.@.@@@@@@..@@.@...@@@@.@@.
@.@.@..@@@@@@@@@@@@.@@@@..@@@.@@@@.@@@..@@.@.@@@@..@@...@@.@@@@.@.@@@@@.@@.@@@.@@.@@@@.@@@@.@@@@@@.@@@...@@@@@.@@@..@.@@..@@.@@@@@@@...@@@.@
@@.@..@@@@.@@@@...@..@@..@@.@@@@.@@@...@@@@@@@@@@@.@.....@@.@@@@@..@@@@@..@@@.....@@..@@@@.@@.@@..@@..@..@.@@@@@....@@@@@.@..@.@.@@.@.@@@@@@
@.@@.@@.@@@.@@..@@@@@@@@@@@@@.@.@.@.@..@@@@@@@@..@...@@@@.@.@.@@.@@@@..@..@@@@@...@@.@@@@....@@@@@@..@.@@@@@@@..@@@.@..@@..@..@@.@@@@@.@@@@.
..@@@.@.@@...@@@@.@@@..@@.@..@@.@@@.@@.@..@.@@..@.@.@@@@@.@@@.@@@.@@@@@.@@..@.@@@@.@@@.@@@@@..@@.@@@...@@.@@@@@...@@@@@@@@@@@@..@@@@@@.@@@@@
.@.@....@@@..@@.@.@@@@@@@@@@@@@@@@.@@@@@.@@@@.@@@@@@@@@@@@@.@.......@@@@.@@@@@..@@@.@.@@@.@@@@@@@@@.@@@.@@....@....@.@@@@@@@.@@@.@@@@@@@@..@
.@..@@@@.@@.@@.@......@..@.@.@@@..@@@@.@@@@@@@...@@@.@@@@@.@@.@@.@@@@@@.@.@@...@@@...@.@..@@.@@..@@@@@...@@.@@@.@@..@@@@@.@@@@@.@@.@...@@.@.
@@@@@.@@@@@@.@@@@@@...@@@@@@@.@@.@@.@@@@.@...@@@@@..@@.@.@@.....@....@.@.@.@.@..@@.@@.@@@@...@@@@.@.@@@@@@...@@@.@@@@@@@.@..@..@@@@@@.@..@.@
@@.@@.@@@.@@@@.@@@@.@@@.@.@@@...@@@@@@.@.@.@@@@@.@.@@@@.@@..@.@..@@@@.@@..@.@@@.@@@.@.@@@..@.@.@@.@.@@@@@@..@..@@..@@@..@.@@@@@..@@.@@@@@..@
.@@.@@@.@@.@.@@@@.@@.@...@@@@.@..@@@..@.@..@..@@.@...@.@@.@@..@..@@.@..@@@@@.@@@@.@@@.@.@@@@...@.@@@....@..@@@@.@@@@@@.@.@..@@..@.@@@@...@@@
..@@.@@.@.@@...@...@..@.@.@@.@..@..@@@@.@...@.@@@@@@@.@@@@.@...@.@..@@@@@.@.@@@@.@.@@.@.@@..@.@@@...@.@@@@@.@..@@@@.@@@@@@@..@@@.@@.@.@..@@.
@@@@.@@@...@.@...@@@@@@@@@@.@@..@@.@.@.@@@@@@..@.@.@.@@.@.@@@@..@@.@@@.@.@@.....@@.@@@..@@.@.@.@.@.@.@@@..@@@@@@@.@@@@@.@@.@@@@..@@@@@@@@.@@
@...@@@...@@.@@@@..@..@.@@@@@@@.@.@@@@.@@@@@@..@@...@@@@@@@@.@@@@@.@@@@.@@.@@..@@@@.@@.@..@@...@@@.@.@@.@..@@@@@@@@@.@..@@.@@.@@..@@@.@.@@..
@..@@@@@.@..@@@@@@.@@.@..@@@@@.....@..@..@@.@@.@.@@.@@.@@@@@@@....@@..@@.@@..@@@@@@@@@@@@@.@.@@@@@@@.@@@.@@.@@@@@@@@@@@@@@@@@.@@@@@@@.@.@@@.
.@@@@@.@@.@@@@...@.@@.@..@@@@..@@@..@.@@@.@@@@@@@.@...@..@@@@..@...@@..@@.@..@@@@.@.@....@.@@@@@.@@@@@@@@@..@@.@@@@..@@.@..@@@.@..@@@@.@@.@@
.@@@...@..@@@@@@@@@@...@...@@@@..@@@.@@@@.@@.....@@@@.@...@...@@...@@@@@...@.@@.@.@.@@.@.@.@@.@@.@@@@@.@@@@@@..@@@@@.@.@@@...@.@.@@.@@@@.@@@
@.@..@@@.@.@..@.@..@@@@@@@@..@...@.@.@@@...@@@.@@@@..@@@.@@@@@@.@.@@@..@@@@@..@......@@.@.@.@@@@@@..@@@@.@@@..@@@.@@.@.@@@@.@@@@...@..@@@@@@
@@@@@@@.@.@.@@@@@@.@.@@..@@@@.@@@@@.@@@@@.@@.@@..@@@@@@.@.@..@@@.@.@.@@@@.@@@..@@@@.@@@@.@@..@.@@@@@..@@@@@@.@...@@@...@.....@@@..@@.@@.@.@.
@@...@.@..@@@.@@.@@@@@.@@@@@@@@@@.@@.@@@.@@.@@..@@@@...@.@.@@@.@..@.@.@@@@@...@@.@@.@.@.@@@@@@.@@@@@@@.....@@@@@.@@.@@.@@.@@@..@@@@.@@@.@@.@
.@@..@@.@@@@@.@@@..@@.@@..@@@@..@@@@@@@..@.@.@@@@..@.@@@.@.@.@..@..@@.@.@@.@.@@@@@..@@@..@@.@.@@.@@.@@..@@.@@@@@@..@@.@.@.@@@.@.@@@@@@.@..@@
@.@@.@@.@@.@@..@.@@.@@.@.@@@.@@@.@.@...@..@.@.@.@..@....@@@.@..@@@@@@@.@@..@@@@@.@..@@@.@..@.@@@@@@@@@.@@@@@@@@@@..@@@@@.@....@@@.@.@.@.@@@@
@@.@......@@@.@@.@..@...@@@@@@@@@@@@@...@@.@@.@@@@@@.@.@@@@@.@.@@@@.@.@@.@@@@.@@@.@..@@..@....@.@.@@@@@.@..@@@@.@@@@.@..@@@@@..@..@.@..@.@.@
@@@@@@@..@.@@@@@@@.@@@@@.@@@..@.@.@@.@.@@@..@@@@@.@@@....@@@@..@.@@...@@.@@@.@@@@.@@.@@@....@@@.@@@@@....@@@@@@...@@@@@@@@@@@..@@.@@@.@@@@@@
.@@@...@@.@@..@@@.@@..@@@..@..@.@@@@..@.@..@.@@@.@@@.@...@@@@@@@@.@@@.@.@.@..@.@@...@.@@@@@@@@@.@@@@@..@.@.@@.@@..@@.@....@@.@@@@@@..@@@@@.@
"""

In [24]:
import numpy as np
from scipy.signal import convolve2d


def solve_my_puzzle(my_puzzle):
  lines = [list(line) for line in my_puzzle.strip().split("\n") if line]
  matrix = (np.array(lines)=='@').astype(int)
  print(matrix)

  kernal = np.array([[1,1,1],
                     [1,0,1],
                     [1,1,1]
                     ])

  count_adjacent_positions = convolve2d(matrix, kernal, mode='same')
  print(f"adjacent positions \n {count_adjacent_positions}")

  accessible_rolls = (matrix == 1) & (count_adjacent_positions < 4)
  print(f"accessible_rolls \n {accessible_rolls}")
  return np.sum(accessible_rolls)



extractor = solve_my_puzzle(my_puzzle)
print(extractor)


[[1 1 0 ... 1 0 0]
 [0 0 1 ... 1 0 1]
 [0 0 0 ... 1 1 1]
 ...
 [1 1 0 ... 1 0 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 0 1]]
adjacent positions 
 [[1 2 2 ... 3 3 1]
 [2 3 2 ... 5 6 2]
 [2 4 5 ... 6 7 4]
 ...
 [4 6 7 ... 6 8 4]
 [4 6 7 ... 5 6 3]
 [3 4 5 ... 4 5 2]]
accessible_rolls 
 [[ True  True False ...  True False False]
 [False False  True ... False False  True]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False  True]
 [False False False ... False False  True]]
1578


Day 4 - Puzzle 2

In [25]:
import numpy as np
from scipy.signal import convolve2d


def solve_my_puzzle(my_puzzle):
  lines = [list(line) for line in my_puzzle.strip().split("\n") if line]
  matrix = (np.array(lines)=='@').astype(int)
  print(matrix)

  kernal = np.array([[1,1,1],
                     [1,0,1],
                     [1,1,1]
                     ])
  total_removed_rolls = 0

  while True:
    count_adjacent_positions = convolve2d(matrix, kernal, mode='same')
    print(f"adjacent positions \n {count_adjacent_positions}")
    accessible_rolls = (matrix == 1) & (count_adjacent_positions < 4)
    current_accessible_rolls = np.sum(accessible_rolls)
    print(f"accessible_rolls \n {current_accessible_rolls}")

    if current_accessible_rolls == 0:
      break

    matrix[accessible_rolls] = 0
    total_removed_rolls += current_accessible_rolls
    print(f"total removable rolls is {total_removed_rolls}")



  return total_removed_rolls



extractor = solve_my_puzzle(my_puzzle)
print(extractor)

[[1 1 0 ... 1 0 0]
 [0 0 1 ... 1 0 1]
 [0 0 0 ... 1 1 1]
 ...
 [1 1 0 ... 1 0 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 0 1]]
adjacent positions 
 [[1 2 2 ... 3 3 1]
 [2 3 2 ... 5 6 2]
 [2 4 5 ... 6 7 4]
 ...
 [4 6 7 ... 6 8 4]
 [4 6 7 ... 5 6 3]
 [3 4 5 ... 4 5 2]]
accessible_rolls 
 1578
total removable rolls is 1578
adjacent positions 
 [[0 0 0 ... 2 1 0]
 [0 0 1 ... 3 4 2]
 [1 2 4 ... 6 6 3]
 ...
 [3 5 6 ... 6 7 3]
 [4 6 7 ... 5 4 2]
 [3 4 5 ... 4 3 1]]
accessible_rolls 
 1286
total removable rolls is 2864
adjacent positions 
 [[0 0 0 ... 0 0 0]
 [0 0 1 ... 2 2 1]
 [0 1 3 ... 4 4 3]
 ...
 [3 4 6 ... 6 6 3]
 [3 5 7 ... 5 3 1]
 [3 4 5 ... 4 3 1]]
accessible_rolls 
 1043
total removable rolls is 3907
adjacent positions 
 [[0 0 0 ... 0 0 0]
 [0 0 1 ... 2 2 1]
 [0 1 3 ... 4 3 2]
 ...
 [2 2 4 ... 4 4 1]
 [3 4 5 ... 4 3 0]
 [2 3 4 ... 3 2 0]]
accessible_rolls 
 837
total removable rolls is 4744
adjacent positions 
 [[0 0 0 ... 0 0 0]
 [0 0 1 ... 1 1 0]
 [0 1 3 ... 1 2 0]
 ...
 [1 2 2 ... 2 2 0]